In [28]:
 import numpy as np
 import pandas as pd
 import seaborn as sns
 import matplotlib.pyplot as plt

In [3]:
 df= pd.read_csv(r"C:\Users\hp\Desktop\Tech war\Telecom_Customer_Support_Tickets_Gigantic_Dataset - Telecom_Customer_Support_Tickets_Gigantic_Dataset.csv.csv")

In [7]:
df.head()

,Ticket_ID,Created_Date,Region,City,Issue_Category,Priority,Resolution_Time_Hours,Customer_Type,Satisfaction_Score
0,500000,2022-07-27,NaN,Pune,Billing,Medium,36.0,Existing,5.0
1,500001,2024-04-04,NaN,Chennai,NaN,Medium,10.0,Existing,2.0
2,500002,2024-02-12,Central,Ahmedabad,Network,High,41.0,New,2.0
3,500003,2022-02-18,Central,Bengaluru,Service,Low,206.0,New,4.0
4,500004,2023-01-04,Central,Chennai,Hardware,Critical,31.0,Existing,5.0

In [5]:
df.shape

(62500, 9)

In [8]:
df.info

<bound method DataFrame.info of        Ticket_ID Created_Date   Region       City Issue_Category  Priority  \
0         500000   2022-07-27      NaN       Pune        Billing    Medium
1         500001   2024-04-04      NaN    Chennai            NaN    Medium
2         500002   2024-02-12  Central  Ahmedabad        Network      High
3         500003   2022-02-18  Central  Bengaluru        Service       Low
4         500004   2023-01-04  Central    Chennai       Hardware  Critical
...          ...          ...      ...        ...            ...       ...
62495     501126   2023-01-02     West  Hyderabad        Service       Low
62496     506196   2024-01-11     West        NaN       Hardware    Medium
62497     516269   2022-06-11  Central    Kolkata        Billing       Low
62498     542189   2022-05-25    South       Pune            NaN       Low
62499     534990   2022-03-05     West     Mumbai        Billing    Medium

       Resolution_Time_Hours Customer_Type  Satisfaction_Score
0                       36.0      Existing                 5.0
1                       10.0      Existing                 2.0
2                       41.0           New                 2.0
3                      206.0           New                 4.0
4                       31.0      Existing                 5.0
...                      ...           ...                 ...
62495                  218.0      Existing                 4.0
62496                   10.0           NaN                 NaN
62497                   92.0           New                 1.0
62498                  100.0           New                 3.0
62499                   19.0      Existing                 5.0

[62500 rows x 9 columns]>

In [9]:
df.isnull().sum()

Ticket_ID                    0
Created_Date                 0
Region                   12543
City                      6921
Issue_Category            6310
Priority                     0
Resolution_Time_Hours      278
Customer_Type             6126
Satisfaction_Score        6231
dtype: int64

In [10]:
df.isnull().sum()/df.shape[0]*100

Ticket_ID                 0.0000
Created_Date              0.0000
Region                   20.0688
City                     11.0736
Issue_Category           10.0960
Priority                  0.0000
Resolution_Time_Hours     0.4448
Customer_Type             9.8016
Satisfaction_Score        9.9696
dtype: float64

In [49]:
df.dropna(inplace=True)
df.isnull().sum()

Ticket_ID                0
Created_Date             0
Region                   0
City                     0
Issue_Category           0
Priority                 0
Resolution_Time_Hours    0
Customer_Type            0
Satisfaction_Score       0
dtype: int64

In [11]:
df.describe()

           Ticket_ID  Resolution_Time_Hours  Satisfaction_Score
count   62500.000000           62222.000000        56269.000000
mean   530003.994160             119.250201            3.220548
std     17317.636308              68.837770            1.226304
min    500000.000000               1.000000            1.000000
25%    515004.750000              60.000000            2.000000
50%    530018.500000             119.000000            3.000000
75%    544988.000000             179.000000            4.000000
max    559999.000000             239.000000            5.000000

In [12]:
df.columns

Index(['Ticket_ID', 'Created_Date', 'Region', 'City', 'Issue_Category',
       'Priority', 'Resolution_Time_Hours', 'Customer_Type',
       'Satisfaction_Score'],
      dtype='object')

In [ ]:
plt.figure(figsize=(10,10))
plt.bar(x='city',y='area',data=df)
plt.show()

In [ ]:
plt.figure(figsize=(10,10))
plt.pie(x="issue category",labels=['Issue category'], autopct='%1.1f%%')
plt.show()